global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: mesh-hub
    static_configs:
      - targets: ['mesh-hub:9100']
  - job_name: mesh-worker
    static_configs:
      - targets: ['mesh-worker:9100']
  - job_name: mesh-trainer
    static_configs:
      - targets: ['mesh-trainer:9100']
  - job_name: mesh-gateway
    static_configs:
      - targets: ['mesh-gateway:9100']
  - job_name: orchestrator
    static_configs:
      - targets: ['dspy-agent:8765']
    metrics_path: /metrics
  - job_name: kafka
    static_configs:
      - targets: ['kafka:9101']
