services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - dspy-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ..
      dockerfile: frontend/backend.Dockerfile
    expose:
      - "8080"
    networks:
      - dspy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport urllib.request as u\nimport sys\ntry:\n  u.urlopen('http://localhost:8080/api/status', timeout=2)\n  sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    command: ["python", "/app/enhanced_dashboard_server.py", "8080"]
    depends_on:
      - frontend

networks:
  dspy-network:
    driver: bridge
