[project]
name = "dspy-code"
version = "0.1.0"
description = "Simple local coding agent using DSPy that reads logs and proposes plans/commands."
readme = "README.md"
requires-python = ">=3.11,<3.13"
license = "Apache-2.0"
authors = [
    { name = "Your Name" }
]
dependencies = [
    "dspy-ai>=2.4.9",
    "typer>=0.12.3",
    "rich>=13.7.1",
    "pydantic>=2.7.4",
    "sentence-transformers>=2.7.0",
    "transformers>=4.51.0",
    "confluent-kafka>=2.3.0",
    "psutil>=5.9.5",
]

[project.scripts]
dspy-agent = "dspy_agent.cli:app"
dspy-coder = "dspy_agent.cli:app"
dspy_coder = "dspy_agent.cli:app"
dspy-code = "dspy_agent.cli:code_entry"

[project.urls]
Homepage = "https://github.com/RPasquale/dspy_stuff"
Repository = "https://github.com/RPasquale/dspy_stuff.git"
DSPy = "https://github.com/stanfordnlp/dspy.git"
RedDB = "https://github.com/redbco/redb-open.git"

[project.optional-dependencies]
rl = [
    "pufferlib>=0.5.0",
    "gymnasium>=0.27",
    "torch>=2.0.0",
    "verifiers @ git+https://github.com/willccbb/verifiers.git",
]

[tool.uv]
dev-dependencies = []
package = true

[tool.setuptools]
packages = []

[tool.setuptools.packages.find]
include = ["dspy_agent", "dspy_agent.*"]
