services:
  reddb:
    image: redbco/redb-open:latest
    container_name: reddb-stack
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - REDB_ADMIN_TOKEN=${REDDB_ADMIN_TOKEN}
      - REDB_LOG_LEVEL=info
    volumes:
      - reddb_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'Authorization: Bearer ${REDDB_ADMIN_TOKEN}' http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  reddb_data: {}
