// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mesh.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcNode       uint64                 `protobuf:"varint,1,opt,name=src_node,json=srcNode,proto3" json:"src_node,omitempty"`
	DstNode       uint64                 `protobuf:"varint,2,opt,name=dst_node,json=dstNode,proto3" json:"dst_node,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	RequireAck    bool                   `protobuf:"varint,4,opt,name=require_ack,json=requireAck,proto3" json:"require_ack,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetSrcNode() uint64 {
	if x != nil {
		return x.SrcNode
	}
	return 0
}

func (x *SendRequest) GetDstNode() uint64 {
	if x != nil {
		return x.DstNode
	}
	return 0
}

func (x *SendRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendRequest) GetRequireAck() bool {
	if x != nil {
		return x.RequireAck
	}
	return false
}

func (x *SendRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SendRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SubscribeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type Received struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	SrcNode       uint64                 `protobuf:"varint,2,opt,name=src_node,json=srcNode,proto3" json:"src_node,omitempty"`
	DstNode       uint64                 `protobuf:"varint,3,opt,name=dst_node,json=dstNode,proto3" json:"dst_node,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Received) Reset() {
	*x = Received{}
	mi := &file_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Received) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Received) ProtoMessage() {}

func (x *Received) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Received.ProtoReflect.Descriptor instead.
func (*Received) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *Received) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Received) GetSrcNode() uint64 {
	if x != nil {
		return x.SrcNode
	}
	return 0
}

func (x *Received) GetDstNode() uint64 {
	if x != nil {
		return x.DstNode
	}
	return 0
}

func (x *Received) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Received) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Received) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	NodeId        uint64                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *AckRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type PublishStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	StateBlob     []byte                 `protobuf:"bytes,3,opt,name=state_blob,json=stateBlob,proto3" json:"state_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStateRequest) Reset() {
	*x = PublishStateRequest{}
	mi := &file_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStateRequest) ProtoMessage() {}

func (x *PublishStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStateRequest.ProtoReflect.Descriptor instead.
func (*PublishStateRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *PublishStateRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PublishStateRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PublishStateRequest) GetStateBlob() []byte {
	if x != nil {
		return x.StateBlob
	}
	return nil
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopologyRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type Topology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Neighbors     []uint64               `protobuf:"varint,1,rep,packed,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topology) Reset() {
	*x = Topology{}
	mi := &file_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *Topology) GetNeighbors() []uint64 {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type SetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	PolicyBlob    string                 `protobuf:"bytes,2,opt,name=policy_blob,json=policyBlob,proto3" json:"policy_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPolicyRequest) Reset() {
	*x = SetPolicyRequest{}
	mi := &file_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPolicyRequest) ProtoMessage() {}

func (x *SetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *SetPolicyRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SetPolicyRequest) GetPolicyBlob() string {
	if x != nil {
		return x.PolicyBlob
	}
	return ""
}

var File_mesh_proto protoreflect.FileDescriptor

const file_mesh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesh.proto\x12\amesh.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xb1\x01\n" +
	"\vSendRequest\x12\x19\n" +
	"\bsrc_node\x18\x01 \x01(\x04R\asrcNode\x12\x19\n" +
	"\bdst_node\x18\x02 \x01(\x04R\adstNode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1f\n" +
	"\vrequire_ack\x18\x04 \x01(\bR\n" +
	"requireAck\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"/\n" +
	"\fSendResponse\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\"C\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"\xae\x01\n" +
	"\bReceived\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x19\n" +
	"\bsrc_node\x18\x02 \x01(\x04R\asrcNode\x12\x19\n" +
	"\bdst_node\x18\x03 \x01(\x04R\adstNode\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"F\n" +
	"\n" +
	"AckRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x04R\x06nodeId\"e\n" +
	"\x13PublishStateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"state_blob\x18\x03 \x01(\fR\tstateBlob\",\n" +
	"\x12GetTopologyRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"(\n" +
	"\bTopology\x12\x1c\n" +
	"\tneighbors\x18\x01 \x03(\x04R\tneighbors\"K\n" +
	"\x10SetPolicyRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1f\n" +
	"\vpolicy_blob\x18\x02 \x01(\tR\n" +
	"policyBlob2\xb2\x01\n" +
	"\bMeshData\x123\n" +
	"\x04Send\x12\x14.mesh.v1.SendRequest\x1a\x15.mesh.v1.SendResponse\x12=\n" +
	"\tSubscribe\x12\x19.mesh.v1.SubscribeRequest\x1a\x11.mesh.v1.Received(\x010\x01\x122\n" +
	"\x03Ack\x12\x13.mesh.v1.AckRequest\x1a\x16.google.protobuf.Empty2\xd2\x01\n" +
	"\vMeshControl\x12D\n" +
	"\fPublishState\x12\x1c.mesh.v1.PublishStateRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\vGetTopology\x12\x1b.mesh.v1.GetTopologyRequest\x1a\x11.mesh.v1.Topology\x12>\n" +
	"\tSetPolicy\x12\x19.mesh.v1.SetPolicyRequest\x1a\x16.google.protobuf.EmptyB\x82\x01\n" +
	"\vcom.mesh.v1B\tMeshProtoP\x01Z+github.com/dspy/orchestrator/internal/pb;pb\xa2\x02\x03MXX\xaa\x02\aMesh.V1\xca\x02\aMesh\\V1\xe2\x02\x13Mesh\\V1\\GPBMetadata\xea\x02\bMesh::V1b\x06proto3"

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData []byte
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)))
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mesh_proto_goTypes = []any{
	(*SendRequest)(nil),         // 0: mesh.v1.SendRequest
	(*SendResponse)(nil),        // 1: mesh.v1.SendResponse
	(*SubscribeRequest)(nil),    // 2: mesh.v1.SubscribeRequest
	(*Received)(nil),            // 3: mesh.v1.Received
	(*AckRequest)(nil),          // 4: mesh.v1.AckRequest
	(*PublishStateRequest)(nil), // 5: mesh.v1.PublishStateRequest
	(*GetTopologyRequest)(nil),  // 6: mesh.v1.GetTopologyRequest
	(*Topology)(nil),            // 7: mesh.v1.Topology
	(*SetPolicyRequest)(nil),    // 8: mesh.v1.SetPolicyRequest
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_mesh_proto_depIdxs = []int32{
	0, // 0: mesh.v1.MeshData.Send:input_type -> mesh.v1.SendRequest
	2, // 1: mesh.v1.MeshData.Subscribe:input_type -> mesh.v1.SubscribeRequest
	4, // 2: mesh.v1.MeshData.Ack:input_type -> mesh.v1.AckRequest
	5, // 3: mesh.v1.MeshControl.PublishState:input_type -> mesh.v1.PublishStateRequest
	6, // 4: mesh.v1.MeshControl.GetTopology:input_type -> mesh.v1.GetTopologyRequest
	8, // 5: mesh.v1.MeshControl.SetPolicy:input_type -> mesh.v1.SetPolicyRequest
	1, // 6: mesh.v1.MeshData.Send:output_type -> mesh.v1.SendResponse
	3, // 7: mesh.v1.MeshData.Subscribe:output_type -> mesh.v1.Received
	9, // 8: mesh.v1.MeshData.Ack:output_type -> google.protobuf.Empty
	9, // 9: mesh.v1.MeshControl.PublishState:output_type -> google.protobuf.Empty
	7, // 10: mesh.v1.MeshControl.GetTopology:output_type -> mesh.v1.Topology
	9, // 11: mesh.v1.MeshControl.SetPolicy:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
