# syntax=docker/dockerfile:1
FROM rust:1.75 AS build

WORKDIR /workspace
COPY Cargo.toml Cargo.lock build.rs ./
COPY src ./src
COPY ../proto ../proto

RUN cargo build --release --bin env_runner

FROM gcr.io/distroless/cc-debian12
COPY --from=build /workspace/target/release/env_runner /usr/local/bin/env-runner
ENTRYPOINT ["/usr/local/bin/env-runner"]
