{{- if .Values.sparkApps.codeLogTrain.enabled }}
apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: code-log-train-schedule
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.sparkApps.codeLogTrain.schedule | default "0 5 * * *" | quote }}
  concurrencyPolicy: Forbid
  template:
    type: Python
    mode: cluster
    image: {{ .Values.image.train }}
    imagePullPolicy: IfNotPresent
    sparkConf:
      spark.sql.adaptive.enabled: "true"
    mainApplicationFile: local:///opt/app/dspy_agent/training/train_code_to_log_hf.py
    sparkVersion: 3.5.1
    arguments:
      - "--dataset-dir"
      - {{ printf "%s/datasets/code_log_predict" .Values.warehouseBase | quote }}
      - "--model"
      - {{ .Values.sparkApps.codeLogTrain.model | default "Salesforce/codet5p-220m" | quote }}
      - "--epochs"
      - {{ .Values.sparkApps.codeLogTrain.epochs | default 1 | quote }}
      - "--batch"
      - {{ .Values.sparkApps.codeLogTrain.batch | default 4 | quote }}
      - "--max-code"
      - {{ .Values.sparkApps.codeLogTrain.maxCode | default 1024 | quote }}
      - "--max-log"
      - {{ .Values.sparkApps.codeLogTrain.maxLog | default 256 | quote }}
      - "--lr"
      - {{ .Values.sparkApps.codeLogTrain.lr | default 2e-4 | quote }}
    driver:
      cores: 1
      memory: 4g
      serviceAccount: {{ .Values.serviceAccount }}
    executor:
      instances: 1
      cores: 1
      memory: 4g
    volumes:
      - name: warehouse
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.warehouse.claim }}
    driver:
      volumeMounts:
        - name: warehouse
          mountPath: {{ .Values.warehouseBase }}
    executor:
      volumeMounts:
        - name: warehouse
          mountPath: {{ .Values.warehouseBase }}
{{- end }}

