apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: feature-build-ingest-files
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.sparkApps.metricsSchedule.schedule | default "*/15 * * * *" | quote }}
  concurrencyPolicy: Forbid
  template:
    type: Python
    mode: cluster
    image: {{ .Values.image.spark }}
    imagePullPolicy: IfNotPresent
    sparkConf:
      spark.sql.adaptive.enabled: "true"
    mainApplicationFile: local:///opt/app/streaming/topics/feature_build_ingest_files.py
    sparkVersion: 3.5.1
    driver:
      cores: 1
      memory: 2g
      serviceAccount: {{ .Values.serviceAccount }}
      env:
        - name: WAREHOUSE_BASE
          value: {{ .Values.warehouseBase | quote }}
    executor:
      instances: 1
      cores: 1
      memory: 2g
    volumes:
      - name: warehouse
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.warehouse.claim }}
    driver:
      volumeMounts:
        - name: warehouse
          mountPath: {{ .Values.warehouseBase }}
    executor:
      volumeMounts:
        - name: warehouse
          mountPath: {{ .Values.warehouseBase }}

