apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vllm-server
  ports:
    - name: http
      port: {{ .Values.vllm.port }}
      targetPort: {{ .Values.vllm.port }}
  type: ClusterIP

