name: Docker Lightweight Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build lightweight image
        uses: docker/build-push-action@v6
        with:
          context: docker/lightweight
          file: docker/lightweight/Dockerfile
          push: false
          load: true
          tags: dspy-lightweight:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'dspy-lightweight:ci'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-image.sarif'
          exit-code: '0'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image.sarif'
