name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build sdist/wheel
        run: |
          python -m build
      - name: Publish to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

