name: Build and Push Spark Image

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
    paths:
      - 'streaming/**'
      - 'docker/spark/**'
  pull_request:
    paths:
      - 'streaming/**'
      - 'docker/spark/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/spark/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dspy-spark:latest
            ghcr.io/${{ github.repository_owner }}/dspy-spark:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/dspy-spark:${{ github.ref_name }}
